FROM node:22-alpine
LABEL authors="cliftoncraig"

# Add Yarn using apk
RUN apk add --no-cache yarn

ENV NODE_ENV development
ENV PORT 80

WORKDIR /app
COPY . .
RUN yarn

EXPOSE 80
ENTRYPOINT ["yarn", "run", "dev"]